<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
  




        <div id="listing">
            <ul class="list-group">
                <?php
                if (isset($message)) {

                    $ans = $message;
                
                    $str = "";
                    $count = 0;
                    foreach ($ans as $key => $val) {
                        $info = $val->info;
                        $additional = $val->additional;
                        $variation = $val->variation;

                        $vari = '<div>';
                        for ($i = 0; $i < count($variation); $i++) {
                            $obj = $variation[$i];
                            $vari .= '<div>';
                            foreach ($obj as $key1 => $val1) {
                                $vari .= '<p>' . $key1 . '=' . $val1 . '</p>';
                            }
                            $vari .= '</div>';
                        }
                        $vari .= '</div>';
                        // die();

                        $pop = '<div>';
                        foreach ($additional as $key2 => $val2) {

                            $pop .= '<li class="">' . $key2 . '=' . $val2;
                        }
                        $pop = $pop . '</div>';
                        // die;
                                    // echo $val->name;
                                    $str .= '<li class="list-group-item list-group-item-primary">product name=' . $info->name . '</li>
                                    <li class="list-group-item list-group-item-primary">product category=' . $info->category . '</li>
                                    <li class="list-group-item list-group-item-primary">product price=' . $info->price . '</li>
                                    <li class="list-group-item list-group-item-primary">product stock=' . $info->stock . '</li>
                                    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#myModal'.$count.'">
                                    Quick View
                                </button>  
                                <div class="modal p-0" id="myModal'.$count.'">
                                    <div class="modal-dialog">
                                        <div class="modal-content">
                                            <div class="modal-body">
                                                <div class="bg-warning p-0"><h4>variation</h4>' . $vari . '</div ><div class="bg-success p-0 "><h4>additional</h4>' . $pop . '</div>
                                            </div>
                                        </div>
                                    </div>
                                </div>';

                         
                        $count++;
                    }
                }

                echo $str;


                ?>
            </ul>


        </div>


</body>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>

<script src="../../../public/jsf/insert.js"></script>


</html>