<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <!-- <button type="button" id="update">update</button> -->
    <form action="order" method="post">
        <input type="submit" name="submit" value="create order">
    </form>
    <form action="orderlist" method="post">
        <input type="submit" name="getsubmit" value="see order">
    </form>

    <form action="insert?val=search" method="post">
        <input type="text" name="productname" >
        <input type="submit" name="search" value="serach">
    </form>

    <div>
        <form action="" method="post">
            <div class="row">
                <div class="col-9">
                    <div>
                    <?php echo $this->locale->_("name") ?> <input type="text" name="name" required="required">
                    </div>
                    <div>
                    <?php echo $this->locale->_("category") ?>   <input type="text" name="category" required="required">
                    </div>
                    <div>
                    <?php echo $this->locale->_("price") ?> <input type="text" name="price" required="required">
                    </div>

                    <div>
                    <?php echo $this->locale->_("stock") ?> <input type="text" name="stock" required="required">
                    </div>
                    <div id="additional">

                    </div>
                    <button type="submit" name="" id="create"><?php echo $this->locale->_("addition") ?></button>

                    <input type="hidden" id="max" name="max" value="0">


                    <input type="submit" class="bg-info" name="submit" value="save">
                </div>
                <div class="col-3">

                    <div id="variation">
                        <button type="submit" name="" id="createvariation"><?php echo $this->locale->_("variation") ?></button>
                        <button type="submit" name="" id="deletevariation"><?php echo $this->locale->_("delete") ?></button>
                        <input type="hidden" id="maxvari" name="varimax" value="0">

                    </div>
                </div>

            </div>

        </form>

        <!-- <div>
            <div>
            <input type="text" name="attriname" >
            <input type="text" name="attrival" >
            </div>
            <input type="text" name="attricount" >
        </div> -->



        <div id="listing">
            <ul class="list-group">
                <?php
                if (isset($message)) {

                    $ans = $message;
                    // // echo "<pre>";
                    // foreach ($ans as $key => $val) {
                    //     // echo $val->name;
                    //     $str .= '<li class="list-group-item list-group-item-primary">' . $val->_id . '&nbsp&nbsp' . $val->age . '</li><button type="button" value="" class="btn btn-primary">Primary</button>';
                    // }

                    // die();


                    $str = "";
                    $count = 0;
                    foreach ($ans as $key => $val) {
                        $info = $val->info;
                        $additional = $val->additional;
                        $variation = $val->variation;

                        $vari = '<div>';
                        for ($i = 0; $i < count($variation); $i++) {


                            $obj = $variation[$i];
                            $vari .= '<div>';
                            foreach ($obj as $key1 => $val1) {
                                $vari .= '<p>' . $key1 . '=' . $val1 . '</p>';
                            }
                            $vari .= '</div>';
                        }
                        $vari .= '</div>';
                        // die();

                        $pop = '<div>';
                        foreach ($additional as $key2 => $val2) {

                            // echo $key;
                            // echo "<br>";
                            // echo $val;
                            $pop .= '<li class="">' . $key2 . '=' . $val2;
                        }
                        $pop = $pop . '</div>';
                        // die;
                                    // echo $val->name;
                                    $str .= '<li class="list-group-item list-group-item-primary">product name=' . $info->name . '</li>
                                    <li class="list-group-item list-group-item-primary">product category=' . $info->category . '</li>
                                    <li class="list-group-item list-group-item-primary">product price=' . $info->price . '</li>
                                    <li class="list-group-item list-group-item-primary">product stock=' . $info->stock . '</li>
                                    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#myModal'.$count.'">
                                    Quick View
                                </button>  
                                <div class="modal p-0" id="myModal'.$count.'">
                                    <div class="modal-dialog">
                                        <div class="modal-content">
                                            <div class="modal-body">
                                                <div class="bg-warning p-0"><h4>variation</h4>' . $vari . '</div ><div class="bg-success p-0 "><h4>additional</h4>' . $pop . '</div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                    
                                
                                <form action="delete" method="get">
                                <input type="hidden"  name="id" value="' . $val->_id . '">
                                <input type="submit"  class="btn btn-danger" name="submit" name="submit" value="delete"></form>
                            
                    
                           ';

                        // $vari = "";
                        // $pop = "";
                        $count++;
                    }
                }

                echo $str;


                ?>
            </ul>


        </div>


</body>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>

<script src="../../../public/jsf/insert.js"></script>


</html>