<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>


    <form action="" method="post">
        <input type="text" name="email" placeholder= <?php echo $this->locale->_("email") ?>>
        <input type="text" name="password" placeholder=<?php echo $this->locale->_("password") ?>>
        <input type="submit" name="submit" value=<?php echo $this->locale->_("submit") ?>>
    </form>

</body>

</html>